language: scala
scala:
- 2.12.4

jdk: oraclejdk8

services:
  - postgresql

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
  - npm install jsdom

before_script:
- psql -c 'create database gpdviz_test;' -U postgres
- sbt clean "gpdvizJVM/runMain gpdviz.Gpdviz generate-conf --overwrite"

script: sbt gpdvizJVM/test
