language: scala
scala:
- 2.12.2

jdk: oraclejdk8

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
  - npm install jsdom
before_script:
- sbt clean "gpdvizJVM/runMain gpdviz.server.GpdvizServer generate-conf --overwrite"
script: sbt test
