version: '3.3'

services:
  gpdviz:
    depends_on:
      - gpdviz_db
    volumes:
      - "${GPDVIZ_CONF_DIR}:/opt/gpdviz/conf/"
    ports:
      - "${GPDVIZ_HOST_PORT}:5050"
    environment:
      - GPDVIZ_DB_USERNAME=${GPDVIZ_DB_USERNAME}
      - GPDVIZ_DB_USERPASS=${GPDVIZ_DB_USERPASS}
    container_name: gpdviz
    image: "gpdviz/gpdviz:0.4.4"
    restart: always

  gpdviz_db:
    volumes:
      - "${POSTGRES_DATA}:/var/lib/postgresql/data"
    ports:
      - "${GPDVIZ_HOST_POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_PASSWORD=${GPDVIZ_DB_USERPASS}
      - GPDVIZ_DB_USERNAME=${GPDVIZ_DB_USERNAME}
      - GPDVIZ_DB_USERPASS=${GPDVIZ_DB_USERPASS}
    container_name: gpdviz_db
    image: "gpdviz/gpdviz_db:0.0.1"
    restart: always
